### PR TITLE
Add path.root support

### PR DESCRIPTION
**Pull request by jeffb4**
Reference https://www.terraform.io/docs/configuration/expressions.html#path-root

### CODE REVIEW

**Comment by juliosueiras** [comment]
Thanks =)

**Comment by juliosueiras** [comment]
will merge it in a bit, the issue I am trying to fix about path var is that path.root, path.cwd, and path.module hold special meaning, and they have to have value so the error check will work correctly

**Comment by jeffb4** [comment]
Yeah that's very true. I didn't see an obvious way forward on the underlying problem so I thought I'd PR another special-case to be added when you come up with a fix :)

**Comment by jeffb4** [comment]
Closing since you put a real fix for root in. Thanks!

**Pull request closed without merging**
