### PR TITLE
[fix] add .terraform dir to scan provider target

### PR DESCRIPTION
**Pull request by dohq**
In my environment, running `terraform init` will create a .terraform in the current directory.
This is not a search for providers by default

### CODE REVIEW

**Comment by dohq** [comment]
I was also wondering.
My environment is only Archlinux, but do other operating systems install everything under the home directory?
If there is no difference between OS, I will fix it by removing strings.HasPrefix (dir, homeDir).

**Comment by radeksimko** [comment]
> do other operating systems install everything under the home directory?

Not sure what do you mean by _everything_ here, but (like you said in your initial comment) Terraform creates `.terraform` directory in the current working directory as part of `terraform init` regardless of OS and regardless of whether that current directory is under home directory or outside of it.

**Comment by dohq** [comment]
You're right.
fixed code.

**Comment by juliosueiras** [comment]
Look good, will do a quick test, and merge it

**Comment by dohq** [comment]
Since this modification is taken in by another pull request, this pull request is closed.

**Pull request closed without merging**
